USE myLunch;
GO


-- Q1
DROP PROC IF EXISTS Question1;
GO
CREATE PROCEDURE Question1
AS
	SELECT 	EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPT_CODE
	FROM L_EMPLOYEES
	WHERE MANAGER_ID = 203;
GO


-- Q2
DROP PROC IF EXISTS Question2;
GO
CREATE PROCEDURE Question2
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE HIRE_DATE > '1999-08-16';
GO


-- Q3
DROP PROC IF EXISTS Question3;
GO
CREATE PROCEDURE Question3
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE LAST_NAME LIKE 'n';
GO


-- Q4
DROP PROC IF EXISTS Question4;
GO
CREATE PROCEDURE Question4
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE CREDIT_LIMIT = 17.50;
GO


-- Q5
DROP PROC IF EXISTS Question5;
GO
CREATE PROCEDURE Question5
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE HIRE_DATE = '2008-07-01';
GO


-- Q6
DROP PROC IF EXISTS Question6;
GO
CREATE PROCEDURE Question6
AS
	SELECT *
	FROM L_EMPLOYEES E, L_DEPARTMENTS D
	WHERE E.DEPT_CODE = D.DEPT_CODE
	AND EMPLOYEE_ID IN (203, 204, 205);
GO


-- Q7
DROP PROC IF EXISTS Question7;
GO
CREATE PROCEDURE Question7
AS
	SELECT *
	FROM L_SUPPLIERS
	WHERE SUPPLIER_NAME LIKE '%&%';
GO


-- Q8
DROP PROC IF EXISTS Question8;
GO
CREATE PROCEDURE Question8
AS
	SELECT COUNT(*) AS "WithoutManagers"
	FROM L_EMPLOYEES
	WHERE MANAGER_ID IS NULL;
GO


-- Q9
DROP PROC IF EXISTS Question9;
GO
CREATE PROCEDURE Question9
AS
	SELECT COUNT(DATE_ENTERED) AS "DistinctDates"
	FROM L_LUNCHES;
GO


-- Q10
DROP PROC IF EXISTS Question10;
GO
CREATE PROCEDURE Question10
AS
	SELECT DESCRIPTION, PRICE
	FROM L_FOODS
	WHERE PRICE < (SELECT AVG(PRICE) FROM L_FOODS);
GO


-- Q11
DROP PROC IF EXISTS Question11;
GO
CREATE PROCEDURE Question11
AS
	SELECT DEPT_CODE, LAST_NAME, EMPLOYEE_ID
	FROM L_EMPLOYEES
	WHERE NOT EMPLOYEE_ID = 209
	ORDER BY DEPT_CODE ASC, LAST_NAME DESC;
GO