-- USE [DATABASENAME];


DROP PROC IF EXISTS Question2_ModelAnswer;
GO
CREATE PROCEDURE Question2_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question3_ModelAnswer;
GO
CREATE PROCEDURE Question3_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO


DROP PROC IF EXISTS Question4_ModelAnswer;
GO
CREATE PROCEDURE Question4_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question5_ModelAnswer;
GO
CREATE PROCEDURE Question5_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question6_ModelAnswer;
GO
CREATE PROCEDURE Question6_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question7_ModelAnswer;
GO
CREATE PROCEDURE Question7_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question8_ModelAnswer;
GO
CREATE PROCEDURE Question8_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question9_ModelAnswer;
GO
CREATE PROCEDURE Question9_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question10_ModelAnswer;
GO
CREATE PROCEDURE Question10_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question11_ModelAnswer;
GO
CREATE PROCEDURE Question11_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question12_ModelAnswer;
GO
CREATE PROCEDURE Question12_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question13_ModelAnswer;
GO
CREATE PROCEDURE Question13_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question14_ModelAnswer;
GO
CREATE PROCEDURE Question14_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question15_ModelAnswer;
GO
CREATE PROCEDURE Question15_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question16_ModelAnswer;
GO
CREATE PROCEDURE Question16_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question17_ModelAnswer;
GO
CREATE PROCEDURE Question17_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question18_ModelAnswer;
GO
CREATE PROCEDURE Question18_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question19_ModelAnswer;
GO
CREATE PROCEDURE Question19_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question20_ModelAnswer;
GO
CREATE PROCEDURE Question20_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question21_ModelAnswer;
GO
CREATE PROCEDURE Question21_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO

DROP PROC IF EXISTS Question22_ModelAnswer;
GO
CREATE PROCEDURE Question22_ModelAnswer
AS
	-- MODEL ANSWER QUERY HERE
GO