/*

Student Name: ######
Student ID: ######

*/

DROP PROC IF EXISTS Question1;
GO
CREATE PROCEDURE Question1
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question2;
GO
CREATE PROCEDURE Question2
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question3;
GO
CREATE PROCEDURE Question3
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question4;
GO
CREATE PROCEDURE Question4
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question5;
GO
CREATE PROCEDURE Question5
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question6;
GO
CREATE PROCEDURE Question6
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question7;
GO
CREATE PROCEDURE Question7
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question8;
GO
CREATE PROCEDURE Question8
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question9;
GO
CREATE PROCEDURE Question9
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question10;
GO
CREATE PROCEDURE Question10
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question11;
GO
CREATE PROCEDURE Question11
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question12;
GO
CREATE PROCEDURE Question12
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question13;
GO
CREATE PROCEDURE Question13
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question14;
GO
CREATE PROCEDURE Question14
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question15;
GO
CREATE PROCEDURE Question15
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question16;
GO
CREATE PROCEDURE Question16
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question17;
GO
CREATE PROCEDURE Question17
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question18;
GO
CREATE PROCEDURE Question18
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question19;
GO
CREATE PROCEDURE Question19
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question20;
GO
CREATE PROCEDURE Question20
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question21;
GO
CREATE PROCEDURE Question21
AS
    -- INSERT YOUR ANSWER HERE;
GO

DROP PROC IF EXISTS Question22;
GO
CREATE PROCEDURE Question22
AS
    -- INSERT YOUR ANSWER HERE;
GO
