USE myLunch;
GO


-- Q1
DROP PROC IF EXISTS Question1_ModelAnswer;
GO
CREATE PROCEDURE Question1_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE MANAGER_ID = 203;
GO


-- Q2
DROP PROC IF EXISTS Question2_ModelAnswer;
GO
CREATE PROCEDURE Question2_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE HIRE_DATE BETWEEN '1999-08-16'
	AND '2008-07-01';
GO


-- Q3
DROP PROC IF EXISTS Question3_ModelAnswer;
GO
CREATE PROCEDURE Question3_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE LAST_NAME LIKE '%n%';
GO


-- Q4
DROP PROC IF EXISTS Question4_ModelAnswer;
GO
CREATE PROCEDURE Question4_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE CREDIT_LIMIT < 17.50;
GO


-- Q5
DROP PROC IF EXISTS Question5_ModelAnswer;
GO
CREATE PROCEDURE Question5_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES
	WHERE HIRE_DATE = '2008-07-01';
GO


-- Q6
DROP PROC IF EXISTS Question6_ModelAnswer;
GO
CREATE PROCEDURE Question6_ModelAnswer
AS
	SELECT *
	FROM L_EMPLOYEES E, L_DEPARTMENTS D
	WHERE E.DEPT_CODE = D.DEPT_CODE
	AND EMPLOYEE_ID IN (203, 204, 205)
	AND DEPARTMENT_NAME = 'Sales';
GO


-- Q7
DROP PROC IF EXISTS Question7_ModelAnswer;
GO
CREATE PROCEDURE Question7_ModelAnswer
AS
	SELECT *
	FROM L_SUPPLIERS
	WHERE SUPPLIER_NAME LIKE '%&%';
GO


-- Q8
DROP PROC IF EXISTS Question8_ModelAnswer;
GO
CREATE PROCEDURE Question8_ModelAnswer
AS
	SELECT COUNT(*) AS "WithoutManagers"
	FROM L_EMPLOYEES
	WHERE MANAGER_ID IS NULL;
GO


-- Q9
DROP PROC IF EXISTS Question9_ModelAnswer;
GO
CREATE PROCEDURE Question9_ModelAnswer
AS
	SELECT COUNT(DISTINCT DATE_ENTERED) AS "DistinctDates"
	FROM L_LUNCHES;
GO


-- Q10
DROP PROC IF EXISTS Question10_ModelAnswer;
GO
CREATE PROCEDURE Question10_ModelAnswer
AS
	SELECT DESCRIPTION, PRICE
	FROM L_FOODS
	WHERE PRICE < (SELECT AVG(PRICE) FROM L_FOODS);
GO


-- Q11
DROP PROC IF EXISTS Question11_ModelAnswer;
GO
CREATE PROCEDURE Question11_ModelAnswer
AS
	SELECT DEPT_CODE, LAST_NAME, EMPLOYEE_ID
	FROM L_EMPLOYEES
	WHERE NOT EMPLOYEE_ID = 209
	ORDER BY DEPT_CODE ASC, LAST_NAME DESC;
GO